services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ingest
      POSTGRES_PASSWORD: ingest
      POSTGRES_DATABASE: ingest

  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "3600", "10"]

  ingest-file:
    build:
      dockerfile: Dockerfile.test
    hostname: ingest
    tmpfs:
      - /tmp:mode=777
      - /data:mode=777
    environment:
      OPENALEPH_DB_URI: postgresql://ingest:ingest@postgres/ingest
      FTM_STORE_URI: postgresql://ingest:ingest@postgres/ingest
      LOG_FORMAT: TEXT # TEXT or JSON
      # LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libgomp.so.1
      LD_PRELOAD: /usr/lib/aarch64-linux-gnu/libgomp.so.1
    volumes:
      - "./ingestors:/ingestors/ingestors"
      - "./tests:/ingestors/tests"
      - "./data:/ingestors/data"
      - "./requirements.txt:/ingestors/requirements.txt"
      - "./setup.py:/ingestors/setup.py"
      - "~:/host"
    depends_on:
      - postgres
      - redis
