services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ingest
      POSTGRES_PASSWORD: ingest
      POSTGRES_DATABASE: ingest

  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "3600", "10"]

  ingest-file:
    image: ghcr.io/openaleph/ingest-file:test
    command: bash -c /ingestors/tests/test_e2e.sh
    hostname: ingest
    tmpfs:
      - /tmp:mode=777
    volumes:
      - "./ingestors:/ingestors/ingestors"
      - "./data/archive:/data"
    environment:
      OPENALEPH_DB_URI: postgresql://ingest:ingest@postgres/ingest
      DEBUG: 0
    depends_on:
      - postgres
      - redis
