FROM ghcr.io/openaleph/ingest-file-base:latest

# uncomment when running on Apple Silicon
# ENV LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

COPY . /ingestors
WORKDIR /ingestors
RUN pip3 install --no-cache-dir -r /ingestors/requirements.txt
RUN pip3 install --no-cache-dir /ingestors

RUN pip3 install -r /ingestors/requirements-dev.txt
RUN chown -R app:app /ingestors

ENV ARCHIVE_TYPE=file \
    ARCHIVE_PATH=/data \
    FTM_STORE_URI=postgresql://aleph:aleph@postgres/aleph \
    REDIS_URL=redis://redis:6379/0 \
    TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata

ENV PROCRASTINATE_APP="ingestors.tasks.app"

USER app
ENTRYPOINT [ "/ingestors/docker-entrypoint.sh" ]
CMD ["pytest"]
